image: archlinux
packages:
  - mandoc
  - rsync
  - scdoc
secrets:
  - 5874ac5a-905e-4596-a117-fed1401c60ce # deploy SSH key
sources:
  - https://git.sr.ht/~emersion/soju
tasks:
  - man: |
      cd soju
      git checkout master
      make doc/soju.1
      mandoc -T html -O style=man-style.css <doc/soju.1 >doc/soju.1.html
      make clean
  - upload: |
      cd soju
      git checkout website
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP \
          --delete \
          --delete-excluded \
          --exclude .git \
          . deploy@emersion.fr:/srv/http/soju
triggers:
  - action: email
    condition: failure
    to: "<contact@emersion.fr>"
